### ISSUE TITLE
Allow to set default option for wrap text

### ISSUE THREAD

**Issue by benm5678** [cle-b/httpdbg#130]
When reviewing in the web UI I need to constantly check the wrap text per request to easily see the data.  Would be cool if it wrapped by default, or have that option exposed in config & stored in a cookie for subsequenet runs.

**Comment by cle-b** [comment]
This is a good idea. 

I will add an option to change the default behavior. 

Thanks for this feedback.

**Comment by cle-b** [comment]
You can now change the default behavior for `Wrap Lines` and `Raw data` in `httpdbg 0.18.0`.

https://httpdbg.readthedocs.io/en/latest/ui/

**Comment by benm5678** [comment]
You are awesome, thanks so much for the quick feature....using it already! :)
