### ISSUE TITLE
Feature Request: Collapsible Initiator Groups

### ISSUE THREAD

**Issue by machadocs** [cle-b/httpdbg#141]
It would be great if the UI supported expanding/collapsing requests per initiator group like so:

## All initiator groups expanded

![httpdbg-expanded](https://github.com/user-attachments/assets/26812fc2-6212-40cd-af3c-dbac0109653f)

## `test_product_connection` collapsed

![httpdbg-collapsed](https://github.com/user-attachments/assets/6a82e470-11dd-44e1-a183-024482066912)

Alternatively, a filter for initiator groups could be added to achieve similar ends.

**Comment by cle-b** [comment]
Hello,

This is a great idea, and I have implemented it. 

It is now available in  [httpdbg v0.22.0](https://pypi.org/project/httpdbg/0.22.0/).

![image](https://github.com/user-attachments/assets/93863e4c-5298-4edb-994c-e1f6ef1bc9e2)

Thank you for the suggestion. 

Have a nice day,

**Comment by machadocs** [comment]
0.22.0 looks good, closing.

Thanks!
