### ISSUE TITLE
Feature Request: Allow specifying the listen address

### ISSUE THREAD

**Issue by TheLocehiliosan** [cle-b/httpdbg#143]
Today, it is hardcoded to listen on "localhost". I'm in an environment where I do remote development, so my browser is not on the same server as the code running. I'm also unable to do ssh port forwarding because of server configs.

I would suggest adding an addition command line argument to specify an address (for example, `0.0.0.0` to listen on all ipv4 addresses). This would allow starting httpdbg up, and then allowing remote fetching of the web interface.

**Comment by cle-b** [comment]
Hello,

It looks doable. I will implement it.

cle.

**Comment by cle-b** [comment]
I added a new command line argument, `--host`, to configure the address on which the internal web server will listen.

To start `httpdbg` with a web server that listens on all IPv4 addresses and a different port:
```
pyhttpdbg --host 0.0.0.0 --port 5000
```

@TheLocehiliosan I hope this will help you to use `httpdbg`.

[documentation](https://httpdbg.readthedocs.io/en/latest/ui/#custom-host)

**Comment by TheLocehiliosan** [comment]
Outstanding! I suspect this will be helpful to many people.

Thanks.

**Comment by cle-b** [comment]
New option available in [httpdbg v0.23.0](https://pypi.org/project/httpdbg/0.23.0/).
