### ISSUE TITLE
Feature Request: Counter for List of Requests

### ISSUE THREAD

**Issue by erikcw** [cle-b/httpdbg#155]
Just learned about httpdbg and have been enjoying using it.  This is a small suggestion, but it would be nice to have a counter in the UI displaying the number of recorded requests.

Thanks for the great tool!

**Comment by cle-b** [comment]
Thanks for the nice feedback and suggestion. 

I think your suggestion is a good idea and easy to do, so I implemented it. 

This is available in [httpdbg v0.26.0](https://pypi.org/project/httpdbg/0.26.0/). 

![image](https://github.com/user-attachments/assets/8a60ea71-c35d-4363-a149-c934e5068039)

I hope httpdbg will be useful to you.

**Comment by erikcw** [comment]
Thank you! This is great!
